#!/usr/bin/env python3
"""
CCGM audit spine -- shared path-exclusion helpers (STDLIB ONLY).

Single source of truth for excluded directory NAMES is `exclude-dirs.txt`
(same directory).  This module reads that file and provides:

  Library:
    load_excluded_dirs()      -> list[str]   canonical excluded dir names
    path_is_excluded(path)    -> bool        True if any path SEGMENT is excluded

  CLI:
    exclude.py --gitleaks-config <out>
        Write a gitleaks v8 config that keeps the default ruleset
        ([extend] useDefault = true) but allowlists every excluded dir by
        path regex.  Dropped gitleaks from 22 min -> 34 s in the field report.

    exclude.py --filter <in.jsonl> <out.jsonl>
        Coordinator-side junk-path post-filter (defense-in-depth, #1).
        Drops FINDING records whose location.path contains an excluded
        segment; passes through every record with a "type" field
        (provenance, coverage_gap, skipped) untouched.  Prints a one-line
        summary to stderr: "filter-excluded: dropped N junk-path finding(s)".

The wrappers that walk the filesystem also apply per-tool exclusion flags
(built from the same list by exclude.sh) so the tools never SCAN the junk
dirs in the first place -- that is the performance fix.  This filter is the
correctness backstop that catches anything a tool's own ignore logic misses.
"""

import json
import os
import re
import sys

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_EXCLUDE_LIST = os.path.join(_SCRIPT_DIR, "exclude-dirs.txt")


def load_excluded_dirs():
    """Return the canonical excluded directory names from exclude-dirs.txt."""
    dirs = []
    try:
        with open(_EXCLUDE_LIST, encoding="utf-8") as fh:
            for raw in fh:
                line = raw.split("#", 1)[0].strip()
                if line:
                    dirs.append(line)
    except OSError:
        # Fall back to a hard-coded minimal set so the filter never silently
        # becomes a no-op if the list file is missing.
        dirs = ["node_modules", ".git", ".claude", ".audit", "dist", "build"]
    return dirs


def _build_segment_matcher(dirs):
    """Compile a regex matching any path that contains an excluded segment."""
    alts = "|".join(re.escape(d) for d in dirs)
    # A segment is bounded by start/slash on the left and slash/end on the right.
    return re.compile(r"(^|/)(" + alts + r")(/|$)")


_EXCLUDED_DIRS = load_excluded_dirs()
_SEGMENT_RE = _build_segment_matcher(_EXCLUDED_DIRS)


def path_is_excluded(path):
    """True if any segment of `path` is an excluded directory name."""
    if not path:
        return False
    normalized = str(path).replace("\\", "/")
    return bool(_SEGMENT_RE.search(normalized))


# ---------------------------------------------------------------------------
# CLI: gitleaks config
# ---------------------------------------------------------------------------

def _write_gitleaks_config(out_path):
    dirs = load_excluded_dirs()
    lines = [
        "# Auto-generated by exclude.py from exclude-dirs.txt. Do not edit by hand.",
        "# Keeps gitleaks' default ruleset; allowlists vendored/generated/worktree dirs.",
        "[extend]",
        "useDefault = true",
        "",
        "[allowlist]",
        'description = "skip vendored/generated/worktree dirs (CCGM audit spine)"',
        "paths = [",
    ]
    for d in dirs:
        esc = d.replace(".", r"\.")
        # Triple-quoted TOML string so backslashes are literal (no escaping).
        lines.append("    '''(^|/){0}(/|$)''',".format(esc))
    lines.append("]")
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# CLI: JSONL junk-path filter
# ---------------------------------------------------------------------------

def _filter_jsonl(in_path, out_path):
    dropped = 0
    kept = 0
    with open(in_path, encoding="utf-8") as fin, \
            open(out_path, "w", encoding="utf-8") as fout:
        for raw in fin:
            stripped = raw.strip()
            if not stripped:
                continue
            try:
                rec = json.loads(stripped)
            except json.JSONDecodeError:
                # Pass through malformed lines untouched -- not our job to drop.
                fout.write(stripped + "\n")
                continue
            # Records with a "type" field (provenance, coverage_gap, skipped)
            # always pass through; they have no location to judge.
            if isinstance(rec, dict) and "type" not in rec:
                path = (rec.get("location") or {}).get("path", "")
                if path_is_excluded(path):
                    dropped += 1
                    continue
                kept += 1
            fout.write(stripped + "\n")
    print(
        "filter-excluded: dropped {0} junk-path finding(s), kept {1}".format(
            dropped, kept
        ),
        file=sys.stderr,
    )
    return dropped


def main(argv):
    if len(argv) >= 3 and argv[1] == "--gitleaks-config":
        _write_gitleaks_config(argv[2])
        return 0
    if len(argv) >= 4 and argv[1] == "--filter":
        _filter_jsonl(argv[2], argv[3])
        return 0
    sys.stderr.write(
        "Usage:\n"
        "  exclude.py --gitleaks-config <out.toml>\n"
        "  exclude.py --filter <in.jsonl> <out.jsonl>\n"
    )
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
