#!/usr/bin/env python3
"""emit_likec4.py -- orrery emit stage (plan sections 3.4 / 3.4a / 3.7 / Epic 3).

model.json -> LikeC4 DSL. Writes into <out-dir>/model/:

  spec.c4             the frozen section-3.4a house palette: custom colors
                      declared once in the specification and referenced by
                      NAME in per-kind style blocks. A raw hex literal
                      inside a style block is a parse error at likec4@1.59.2.
  model.c4            elements nested by parent, triple-quoted Markdown
                      descriptions, technology, links.
  views.c4            L1 index, L2 `view of <system>`, L3 per-container.
                      `view <id> of <nested-element>` requires the
                      parent-QUALIFIED FQN (e.g. `of system.web`) even
                      though relation references resolve bare -- verified
                      in the Epic 1 spike record (decisions.md).
  likec4.config.json  {"name": <slug>, "implicitViews": true} -- MUST sit
                      INSIDE model/ (section 3.7): at the parent it is
                      silently ignored and every drill-down view vanishes.

Source links (plan section 3.4): emitted ONLY when the normalized remote
host is exactly github.com, built from the credential-stripped remote_url
with ssh->https normalization, pinned to the anchor SHA. For any other
remote (or no remote) ZERO github.com URLs are emitted -- the model meta
already carries source_links: "none (non-GitHub remote)".

Escaping (section 3.7, security N3): every repo-derived prose string
(title/summary/description/technology, relation summaries, view titles) is
HTML-entity escaped UNCONDITIONALLY (& < >), plus the deterministic DSL
layer: LikeC4 string literals have no escape sequences, so the quote
characters themselves are entity-escaped (" -> &quot;, ' -> &#39;) and
link/path strings are percent-encoded. Emission is byte-deterministic:
sorted ids everywhere, no timestamps.

File tier cap (section 3.3): at most 12 `kind: file` children per parent
are emitted (deterministic by sorted id -- packs already rank by
significance); a truncating parent's description gains a trailing
"showing N of M files" note and relations touching dropped file elements
are skipped so the DSL never dangles.

Stdlib only. Exit 0 on success; 2 on usage/IO errors.
"""

import argparse
import json
import os
import re
import sys
from urllib.parse import quote

MAX_FILE_CHILDREN = 12

# ---------------------------------------------------------------------------
# spec.c4 -- the frozen section-3.4a palette (verified compiling verbatim at
# likec4@1.59.2 in the Epic 1 spike; the golden fixture bakes the same block).
# ---------------------------------------------------------------------------
SPEC_C4 = """\
// generated by emit_likec4.py -- orrery house palette (plan section 3.4a).
// A raw hex literal is NOT valid inside a style block at likec4@1.59.2:
// custom colors are declared once in the specification and referenced by name.
specification {
  color orrery_system    #4C6EF5
  color orrery_actor     #845EF7
  color orrery_container #3B5BDB
  color orrery_component #5C7CFA
  color orrery_datastore #0CA678
  color orrery_queue     #0B7285
  color orrery_cloud     #495057
  color orrery_external  #868E96
  color orrery_package   #ADB5BD
  color orrery_tool      #CED4DA
  color orrery_file      #748FFC

  element system           { style { shape rectangle color orrery_system } }
  element actor            { style { shape person    color orrery_actor } }
  element container        { style { shape rectangle color orrery_container } }
  element component        { style { shape rectangle color orrery_component } }
  element datastore        { style { shape storage   color orrery_datastore } }
  element queue            { style { shape queue     color orrery_queue } }
  element cloud_provider   { style { shape rectangle color orrery_cloud } }
  element external_service { style { shape rectangle color orrery_external } }
  element package          { style { shape rectangle color orrery_package } }
  element tool             { style { shape rectangle color orrery_tool } }
  element file             { style { shape rectangle color orrery_file size sm } }
}
"""

# Kinds shown on the L1 landscape (plan section 3.4: system + actors +
# cloud/external/datastore -- queue included per the golden fixture).
L1_KINDS = {"actor", "cloud_provider", "external_service", "datastore", "queue"}


def esc_prose(text, single_line=False):
    """Unconditional HTML-entity escaping (& < > per section 3.7) plus the
    deterministic DSL layer: quote characters become entities too, because
    LikeC4 string literals have no escape sequences -- a literal quote
    would terminate the string."""
    text = (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )
    if single_line:
        text = re.sub(r"[\r\n]+", " ", text)
    return text


def esc_url(url):
    """Deterministic DSL escaping for link URLs: percent-encode every
    character that could break an unquoted LikeC4 link token (quotes,
    spaces, braces). Existing percent-escapes are preserved."""
    return quote(url, safe=":/?#[]@!$&*+,;=()-._~%=")


# strip_credentials / github_owner_repo are duplicated from
# merge_fragments.py (same module, self-contained scripts by design -- the
# emit stage must not trust that merge ran on this machine).
_SCHEME_USERINFO_RE = re.compile(r"^([A-Za-z][A-Za-z0-9+.-]*://)([^/@]+)@")


def strip_credentials(url):
    if not url:
        return None
    m = _SCHEME_USERINFO_RE.match(url)
    if m:
        return m.group(1) + url[m.end():]
    m = re.match(r"^([^/@:]+):([^/@]+)@(.+)$", url)
    if m:
        return m.group(3)
    return url


def github_owner_repo(url):
    if not url:
        return None
    url = strip_credentials(url)
    host = path = None
    m = re.match(r"^(?:git\+)?ssh://(?:[^@/]+@)?([^/:]+)(?::\d+)?/(.+)$", url)
    if m:
        host, path = m.group(1), m.group(2)
    if host is None:
        m = re.match(r"^https?://([^/:]+)(?::\d+)?/(.+)$", url)
        if m:
            host, path = m.group(1), m.group(2)
    if host is None:
        m = re.match(r"^(?:[^@/:]+@)?([^/:]+):(.+)$", url)
        if m and "/" not in m.group(1):
            host, path = m.group(1), m.group(2)
    if host is None or host.lower() != "github.com":
        return None
    parts = [p for p in path.strip("/").split("/") if p]
    if len(parts) < 2:
        return None
    owner, repo = parts[0], parts[1]
    if repo.endswith(".git"):
        repo = repo[:-4]
    if not owner or not repo:
        return None
    return owner, repo


def source_link_urls(element, gh, anchor_sha):
    """GitHub blob links at the anchor SHA for an element's files.
    Returns [] when gh is None (non-GitHub or no remote: zero links)."""
    if gh is None:
        return []
    owner, repo = gh
    urls = []
    for f in element.get("files") or []:
        path = quote(f["path"], safe="/-._~")
        url = "https://github.com/%s/%s/blob/%s/%s" % (owner, repo, anchor_sha, path)
        start = f.get("start_line")
        end = f.get("end_line")
        if start:
            url += "#L%d" % start
            if end and end != start:
                url += "-L%d" % end
        urls.append(url)
    return urls


class Emitter:
    def __init__(self, model):
        self.meta = model["meta"]
        self.elements = sorted(model.get("elements", []), key=lambda e: e["id"])
        self.relations = model.get("relations", [])
        self.by_id = {e["id"]: e for e in self.elements}
        self.children = {}
        self.roots = []
        for el in self.elements:
            parent = el.get("parent")
            if parent and parent in self.by_id:
                self.children.setdefault(parent, []).append(el)
            else:
                self.roots.append(el)
        # GitHub links only when the merge stage already concluded the
        # remote is GitHub AND the URL re-parses cleanly here.
        self.gh = None
        if self.meta.get("source_links") == "github":
            self.gh = github_owner_repo(self.meta.get("remote_url"))
        # File-tier cap (section 3.3): deterministic by sorted id.
        self.dropped = set()
        self.truncation_notes = {}
        for parent_id, kids in self.children.items():
            file_kids = [k for k in kids if k.get("kind") == "file"]
            if len(file_kids) > MAX_FILE_CHILDREN:
                for k in file_kids[MAX_FILE_CHILDREN:]:
                    self.dropped.add(k["id"])
                self.truncation_notes[parent_id] = (MAX_FILE_CHILDREN, len(file_kids))

    # -- model.c4 -----------------------------------------------------------

    def emit_model(self):
        lines = [
            "// generated by emit_likec4.py -- do not edit (regenerate from model.json)",
            "model {",
        ]
        visited = set()
        for el in self.roots:
            lines.extend(self._emit_element(el, 1, visited))
        rel_lines = self._emit_relations(visited)
        if rel_lines:
            lines.append("")
            lines.extend(rel_lines)
        lines.append("}")
        return "\n".join(lines) + "\n"

    def _emit_element(self, el, depth, visited):
        if el["id"] in visited or el["id"] in self.dropped:
            return []
        visited.add(el["id"])
        ind = "  " * depth
        lines = ["%s%s = %s '%s' {" % (ind, el["id"], el["kind"], esc_prose(el["title"], single_line=True))]
        body = ind + "  "
        tech = el.get("technology")
        if tech:
            lines.append("%stechnology '%s'" % (body, esc_prose(tech, single_line=True)))
        lines.append("%ssummary '%s'" % (body, esc_prose(el["summary"], single_line=True)))
        desc = el.get("description") or ""
        note = self.truncation_notes.get(el["id"])
        if note:
            suffix = "showing %d of %d files" % note
            desc = (desc + "\n\n" + suffix) if desc else suffix
        if desc:
            lines.append("%sdescription '''" % body)
            for dline in esc_prose(desc).split("\n"):
                lines.append((body + "  " + dline).rstrip())
            lines.append("%s'''" % body)
        for url in source_link_urls(el, self.gh, self.meta.get("anchor_sha")):
            lines.append("%slink %s 'source'" % (body, esc_url(url)))
        ext = el.get("external_url")
        if ext:
            lines.append("%slink %s 'docs'" % (body, esc_url(ext)))
        for child in self.children.get(el["id"], []):
            child_lines = self._emit_element(child, depth + 1, visited)
            if child_lines:
                lines.append("")
                lines.extend(child_lines)
        lines.append("%s}" % ind)
        return lines

    def _emit_relations(self, visited):
        lines = []
        seen = set()
        rels = sorted(
            self.relations,
            key=lambda r: (r.get("from") or "", r.get("to") or "", r.get("summary") or ""),
        )
        for rel in rels:
            frm, to = rel.get("from"), rel.get("to")
            if frm not in visited or to not in visited:
                continue  # endpoint dropped by the file cap
            key = (frm, to, rel.get("summary"))
            if key in seen:
                continue
            seen.add(key)
            lines.append("  %s -> %s '%s'" % (frm, to, esc_prose(rel.get("summary") or "", single_line=True)))
        return lines

    # -- views.c4 -----------------------------------------------------------

    def _fqn(self, element_id):
        """Parent-qualified FQN. `view <id> of <nested>` fails to resolve a
        bare nested id at likec4@1.59.2 (Epic 1 spike record) -- the `of`
        target must be the dotted path from the root."""
        chain = []
        cur = element_id
        guard = 0
        while cur is not None and guard <= len(self.by_id):
            chain.append(cur)
            el = self.by_id.get(cur)
            cur = el.get("parent") if el else None
            if cur is not None and cur not in self.by_id:
                cur = None
            guard += 1
        return ".".join(reversed(chain))

    def emit_views(self):
        title = esc_prose(self.meta.get("repo_title") or self.meta.get("slug") or "", single_line=True)
        lines = [
            "// generated by emit_likec4.py -- do not edit (regenerate from model.json)",
            "views {",
            "  view index {",
            "    title '%s - system landscape'" % title,
        ]
        l1 = [e["id"] for e in self.roots
              if e.get("kind") == "system" or e.get("kind") in L1_KINDS]
        if not l1:
            l1 = [e["id"] for e in self.roots]
        lines.append("    include %s" % ", ".join(sorted(l1)))
        lines.append("  }")
        for el in self.elements:
            if el.get("kind") != "system" or el["id"] in self.dropped:
                continue
            lines.append("")
            lines.append("  view %s_containers of %s {" % (el["id"], self._fqn(el["id"])))
            lines.append("    title '%s - containers'" % esc_prose(el["title"], single_line=True))
            lines.append("    include *")
            lines.append("  }")
        for el in self.elements:
            if el.get("kind") != "container" or el["id"] in self.dropped:
                continue
            lines.append("")
            lines.append("  view %s_components of %s {" % (el["id"], self._fqn(el["id"])))
            lines.append("    title '%s - components'" % esc_prose(el["title"], single_line=True))
            lines.append("    include *")
            lines.append("  }")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def emit_config(self):
        # MUST land INSIDE model/ (section 3.7): at the parent it is
        # silently ignored and the L2-L4 drill-down views disappear.
        return json.dumps({"name": self.meta.get("slug"), "implicitViews": True}, indent=2) + "\n"


def run(argv=None):
    ap = argparse.ArgumentParser(prog="emit_likec4.py")
    ap.add_argument("--model", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args(argv)

    try:
        with open(args.model, "r", encoding="utf-8") as fh:
            model = json.load(fh)
    except (OSError, ValueError) as exc:
        print("emit_likec4.py: cannot read model %s: %s" % (args.model, exc), file=sys.stderr)
        return 2

    model_dir = os.path.join(args.out_dir, "model")
    os.makedirs(model_dir, exist_ok=True)

    emitter = Emitter(model)
    outputs = {
        "spec.c4": SPEC_C4,
        "model.c4": emitter.emit_model(),
        "views.c4": emitter.emit_views(),
        "likec4.config.json": emitter.emit_config(),
    }
    for name in sorted(outputs):
        with open(os.path.join(model_dir, name), "w", encoding="utf-8") as fh:
            fh.write(outputs[name])

    print("emit_likec4.py: wrote %s/{spec.c4,model.c4,views.c4,likec4.config.json}" % model_dir)
    if emitter.truncation_notes:
        for pid in sorted(emitter.truncation_notes):
            kept, total = emitter.truncation_notes[pid]
            print("emit_likec4.py: %s truncated to %d of %d file children" % (pid, kept, total))
    if emitter.meta.get("source_links") != "github":
        print("emit_likec4.py: source links: none (non-GitHub remote)")
    return 0


def main():
    sys.exit(run())


if __name__ == "__main__":
    main()
